---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: maven
    tag: latest
    
inputs:
  - name: Maven_Sample1
  
outputs:
  - name: resource-app
  
run:
  path: Maven_Helloworld/Maven_Sample1/ci/build.sh
