---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: maven
    tag: latest
    
inputs:
  - name: maven
  
outputs:
  - name: resource-app
  
run:
  path: sample-app/ci/build.sh
